volumes:
  usage_logs:

services:
  chatgpt-telegram-bot:
    healthcheck:
      test: 'bash /home/appuser/health.sh'
      interval: 90s
      timeout: 60s
      retries: 2
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - usage_logs:/home/appuser/usage_logs:rw
    environment:
      - OPENAI_API_KEY
      - TELEGRAM_BOT_TOKEN
      - ALLOWED_TELEGRAM_USER_IDS
      - ASSISTANT_PROMPT
      - SHOW_USAGE
      - MAX_TOKENS
      - MAX_HISTORY_SIZE
      - MAX_CONVERSATION_AGE_MINUTES
      - VOICE_REPLY_WITH_TRANSCRIPT_ONLY
      - N_CHOICES
      - TEMPERATURE
      - IMAGE_SIZE
      - GROUP_TRIGGER_KEYWORD
      - TOKEN_PRICE
      - IMAGE_PRICES
      - TRANSCRIPTION_PRICE

