volumes:
  usage_logs:

services:
  chatgpt-telegram-bot:
    healthcheck:
#      test: 'curl -m 90 -sLf -H "Authorization: Bearer ${OPENAI_API_KEY}" https://api.openai.com/v1/models && curl -m 90 -sLf "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/getMe"'
      test: 'curl -m 90 -sLf "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/getMe"'
      interval: 5m
      timeout: 60s
      retries: 2
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - usage_logs:/home/appuser/usage_logs:rw
    environment:
      - OPENAI_API_KEY
      - TELEGRAM_BOT_TOKEN
      - ALLOWED_TELEGRAM_USER_IDS
      - ASSISTANT_PROMPT
      - SHOW_USAGE
      - MAX_TOKENS
      - MAX_HISTORY_SIZE
      - MAX_CONVERSATION_AGE_MINUTES
      - VOICE_REPLY_WITH_TRANSCRIPT_ONLY
      - N_CHOICES
      - TEMPERATURE
      - IMAGE_SIZE
      - GROUP_TRIGGER_KEYWORD
      - TOKEN_PRICE
      - IMAGE_PRICES
      - TRANSCRIPTION_PRICE

